root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["--config", "config/config.json"]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main cmd/web/main.go cmd/web/config.go cmd/web/routes.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "archive", "sql", "strategies", "__pycache__"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "pkg", "config"]
  include_ext = ["go", "json", "md"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = ["echo '🧪 Running tests...'", "./run_tests.sh"]
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = false